name: rustdoc

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
